# Generated by Django 2.2.6 on 2019-12-21 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='city',
        ),
        migrations.AddField(
            model_name='cities',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='articles',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cities'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_name',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.Articles'),
            preserve_default=False,
        ),
    ]
