# Generated by Django 2.2.6 on 2019-12-22 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(upload_to='img/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cities')),
            ],
        ),
    ]
