# Generated by Django 2.2.6 on 2019-12-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191222_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
